[versions]
kotlin = "1.5.10"
androidBuildTools = "7.1.0-alpha03"
versions = "0.38.0"
detekt = "1.17.0"
ktlint = "10.0.0"
canidropjetifier = "0.5"

androidx-core = "1.7.0-alpha01"
androidx-activityCompose = "1.3.0-rc01"
material = "1.4.0"
compose = "1.0.0-rc01"
accompanist = "0.13.0"

junit = "4.13.2"
androidx-testExt = "1.1.3"
androidx-test = "1.4.0"
espresso-core = "3.4.0"

compileSdk = "30"
minSdk = "21"
targetSdk = "30"

appVersionCode = "1"
appVersionName = "1.0.0"
applicationId = "com.stylingandroid.compose.strikethru"

[libraries]
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidBuildTools" }
versionsPlugin = { module = "com.github.ben-manes:gradle-versions-plugin", version.ref = "versions" }
detektPlugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
ktlintPlugin = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "ktlint" }
canidropjetifierPlugin = { module = "com.github.plnice:canidropjetifier", version.ref = "canidropjetifier" }

kotlin-sdk = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin"}
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }

androidx-composeUi = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidx-composeMaterial = { module = "androidx.compose.material:material", version.ref = "compose" }
androidx-composeUiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }

accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist"}

testing-junit = { module = "junit:junit", version.ref = "junit" }
testing-androidx-test = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
testing-androidx-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }
testing-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
testing-compose-ui = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
testing-compose-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }

[bundles]
androidx-compose = [
    "androidx-activityCompose",
    "androidx-composeUi",
    "androidx-composeMaterial",
    "androidx-composeUiTooling",
    "accompanist-systemuicontroller"
]
